Description: >

    This template deploys a highly available ECS cluster using an AutoScaling Group, with 
    ECS hosts distributed across multiple Availability Zones. 

    Last Modified: 15th July 2017
    Author: Marcos Sobrinho <marcos.sobrinho@truckpad.com.br>
    Author: Paul Maddox <pmaddox@amazon.com>


Parameters:

    ClusterSize:
        Description: How many ECS hosts do you want to initially deploy?
        Type: Number
        Default: 2

    DatadogApiKey:
        Description: Install Datadog dd-agent using this API Key 
        Type: String            
        Default: none
        AllowedPattern: ^none|[a-f0-9]{32}$

    DatadogEnableAPM:
        Description: Enable Application Performance Monitoring (trace)
        Type: String
        Default: false
        AllowedValues: [false, true]

    InstanceType:
        Description: Instance type to use
        Type: String
        AllowedValues: [t2.large, c4.large, c4.xlarge, c4.2xlarge, m4.large, m4.xlarge, m4.2xlarge]

    KeyName:
        Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS cluster
        Type: AWS::EC2::KeyPair::KeyName

    SubnetPrefix:
        Description: IP address first two blocks, used to build the VPC Subnet IPs
        Type: String
        Default: '10.16'
        AllowedPattern: ^[0-9]{2,3}\.[0-9]{1,3}$


Conditions:
    EnableDatadogAgent: !Not [ !Equals [ !Ref DatadogApiKey, none ] ]


Resources:

    vpc:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/cfn-truckpad/ecs/infrastructure/vpc.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VpcCIDR: !Join ['.', [!Ref SubnetPrefix, '0.0/16']]
                PublicSubnet1CIDR: !Join ['.', [!Ref SubnetPrefix, '8.0/21']]
                PublicSubnet2CIDR: !Join ['.', [!Ref SubnetPrefix, '16.0/21']]
                PrivateSubnet1CIDR: !Join ['.', [!Ref SubnetPrefix, '24.0/21']]
                PrivateSubnet2CIDR: !Join ['.', [!Ref SubnetPrefix, '32.0/21']]

    sgs:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/cfn-truckpad/ecs/infrastructure/security-groups.yaml
            Parameters: 
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt vpc.Outputs.VPC

    alb:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/cfn-truckpad/ecs/infrastructure/load-balancers.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                VPC: !GetAtt vpc.Outputs.VPC
                Subnets: !GetAtt vpc.Outputs.PublicSubnets
                SecurityGroup: !GetAtt sgs.Outputs.LoadBalancerSecurityGroup

    ecs:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://s3.amazonaws.com/cfn-truckpad/ecs/infrastructure/ecs-cluster.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                KeyName: !Ref KeyName
                InstanceType: !Ref InstanceType
                ClusterSize: !Ref ClusterSize
                VPC: !GetAtt vpc.Outputs.VPC
                SecurityGroup: !GetAtt sgs.Outputs.ECSHostSecurityGroup
                Subnets: !GetAtt vpc.Outputs.PrivateSubnets

    ddagent:
        Type: AWS::CloudFormation::Stack
        Condition: EnableDatadogAgent
        Properties:
            TemplateURL: https://s3.amazonaws.com/cfn-truckpad/ecs/services/dd-agent/service.yaml
            Parameters:
                EnvironmentName: !Ref AWS::StackName
                Cluster: !GetAtt ecs.Outputs.Cluster
                VPC: !GetAtt vpc.Outputs.VPC
                ApiKey: !Ref DatadogApiKey
                EnableAPM: !Ref DatadogEnableAPM


Outputs:

    ECSCluster:
        Description: The ECS cluster name that I've created!
        Value: !GetAtt ecs.Outputs.Cluster
